// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  DB: D1Database;
}

declare module "cloudflare:test" {
  // Controls the type of `import("cloudflare:test").env`
  interface ProvidedEnv extends Env {
    DB: D1Database;
    TEST_MIGRATIONS: D1Migration[]; // Defined in `vitest.config.mts`
  }
}
